// config/menu-structure.ts - MENU DEFINITION
export const MENU_STRUCTURE = [
  {
    key: 'dashboard.access',
    title: 'Dashboard',
    icon: 'LayoutDashboard',
    path: '/dashboard',
    is_primary_sidebar: true,
    is_show_with_lock_if_no_access: true,
    order: 1,
  },
  {
    key: 'dashboard.access-control.access',
    title: 'Access Control',
    icon: 'Shield',
    path: '/dashboard/access-control',
    order: 2,
    is_primary_sidebar: true,
    is_show_with_lock_if_no_access: false,
    children: [
      {
        key: 'dashboard.access-control.access',
        title: 'Access Control',
        icon: '',
        path: '',
        is_show_with_lock_if_no_access: false,
        order: 1,
        children: [
          {
            key: 'dashboard.access-control.roles.access',
            title: 'Roles',
            icon: 'Shield',
            path: '/dashboard/access-control/roles',
            is_show_with_lock_if_no_access: false,
            order: 1,
          }, {
            key: 'dashboard.access-control.permissions.access',
            title: 'Permissions',
            icon: 'Key',
            path: '/dashboard/access-control/permissions',
            is_show_with_lock_if_no_access: false,
            order: 2,
          },
          {
            key: 'dashboard.access-control.menu-permissions.access',
            title: 'Menu Permissions',
            icon: 'Menu',
            path: '/dashboard/access-control/menu-permissions',
            is_show_with_lock_if_no_access: false,
            order: 3,
          },
          {
            key: 'dashboard.access-control.users.access',
            title: 'Users',
            icon: 'User',
            path: '/dashboard/access-control/users',
            is_show_with_lock_if_no_access: false,
            order: 4,
          },
        ]
      },
      {
        key: 'dashboard.subscriptions.access',
        title: 'Subscription',
        icon: '',
        path: '/dashboard/access-control',
        order: 2,
        is_show_with_lock_if_no_access: false,
        children: [
          {
            key: 'dashboard.subscriptions.plans.access',
            title: 'Plans',
            icon: 'CreditCard',
            path: '/dashboard/subscription-management/plans',
            is_show_with_lock_if_no_access: false,
            order: 1,
          },
          {
            key: 'dashboard.subscriptions.offers.access',
            title: 'Offers',
            icon: 'Tag',
            path: '/dashboard/subscription-management/offers',
            is_show_with_lock_if_no_access: false,
            order: 2,
          },
          {
            key: 'dashboard.subscriptions.features.access',
            title: 'Features',
            icon: 'Sparkles',
            path: '/dashboard/subscription-management/features',
            is_show_with_lock_if_no_access: false,
            order: 3,
          },
          {
            key: 'dashboard.subscriptions.features-permission.access',
            title: 'Features Permissions',
            icon: 'Lock',
            path: '/dashboard/subscription-management/features-permission',
            is_show_with_lock_if_no_access: false,
            order: 4,
          },
        ]
      },
    ],
  },
  {
    key: 'dashboard.billing.access',
    title: 'Billing',
    icon: 'Wallet',
    path: '/dashboard/billing',
    order: 4,
    is_primary_sidebar: true,
    is_show_with_lock_if_no_access: false,
    children: [
      {
        key: 'dashboard.billing.access',
        title: 'Billing Overview',
        icon: 'CreditCard',
        path: '/dashboard/billing',
        is_show_with_lock_if_no_access: false,
        order: 1,
      },
      {
        key: 'dashboard.billing.plans.access',
        title: 'Plans',
        icon: 'Package',
        path: '/dashboard/billing/plans',
        is_show_with_lock_if_no_access: false,
        order: 2,
      },
      {
        key: 'dashboard.billing.payment-methods.access',
        title: 'Payment Methods',
        icon: 'CreditCard',
        path: '/dashboard/billing/payment-methods',
        is_show_with_lock_if_no_access: false,
        order: 3,
      }
    ]
  },
  {
    key: 'dashboard.chat.access',
    title: 'Chat',
    icon: 'MessagesSquare',
    path: '/dashboard/chat',
    order: 5,
    is_primary_sidebar: true,
    is_show_with_lock_if_no_access: false,
  },
];